resolver: lts-8.18

packages:
- '.'
extra-deps: []

# Override default flag values for local packages and extra-deps
flags:
  proteaaudio:
    example: true

# Extra package databases containing global packages
extra-package-dbs: []
