resolver: lts-12.21

packages:
- '.'

# Override default flag values for local packages and extra-deps
flags:
  proteaaudio-sdl:
    example: true
nix:
  enable: false
  packages: [pulseaudio]
  pure: false
