resolver: nightly-2023-01-06

packages:
- '.'

# Override default flag values for local packages and extra-deps
flags:
  proteaaudio:
    example: true
nix:
  enable: false
  packages: [pulseaudio]
  pure: false
